export const CLASSIFIER_SAMPLE_RATE = 16_000;
export const CLASSIFIER_MEL_BINS = 64;
export const CLASSIFIER_FFT_SIZE = 1024;
export const CLASSIFIER_HOP_SIZE = 512;
export const CLASSIFIER_FRAMES = 96;
export const CLASSIFIER_WINDOW_SAMPLES =
  (CLASSIFIER_FRAMES - 1) * CLASSIFIER_HOP_SIZE + CLASSIFIER_FFT_SIZE;

